#!/bin/sh
#
# Run scraperwiki scrapers with a fake scraperwiki library, to allow
# the scrapers to be tested locally.

file=$1

topdir=`pwd`

export PYTHONPATH=`pwd`/testlib/scraperwiki-python:`pwd`/testlib/dumptruck

mkdir -p data/$1
(cd data/$file ; python $topdir/scrapersources/$file)
